package com.example.practica5.utils

object MonumentsConstant {
    const val DELAY_MILLIS: Long = 1000
    const val FIRST_LIST_POSITION = 0
    const val BASE_URL_RETROFIT = "https://gist.githubusercontent.com/ignaciogs/f766e43d45e09bb4d65296c95b1848d1/raw/"
    const val BASE_URL_FLAGS_API = "https://flagsapi.com/"
    const val MONUMENT_ID = "id"
    const val MONUMENT_NAME = "name"
    const val SORTED_NORTH_SOUTH = "nToS"
    const val SORTED_EAST_WEST = "eToW"
    const val ALL_COUNTRIES = "Todos los países"
    const val DATABASE_NAME = "monuments_dataBase"
    const val EMPTY_INFO = ""
    const val LOCATION_PERMISSION_REQUEST_CODE = 123
    const val MONUMENTS_TITLE = "Monuments"
    const val NEW_MONUMENT_TITLE = "New Monument"
    const val DENIED_LOCATION_PERMISSIONS = "Permiso de ubicación denegado"
    const val EMAIL_SUBJECT = "Aprueba Historia"
    const val MONUMENT_TARGET = "monumentTarget"
    const val SELECT_GALLERY = "Gallery"
    const val TAKE_PHOTO = "Take photo"
    const val PERMISSION_REQUEST_READ_EXTERNAL_STORAGE = 1
    const val PERMISSION_REQUEST_CAMERA = 2
    const val DATE_FORMAT = "yyyyMMdd_HHmmss"
    const val ADD_MONUMENT_MESSAGE = "Monumento añadido!"
    const val INPUT_EMPTY = 0
    const val MAX_CHARACTERS_NAME_CITY_INPUT = 50
    const val MAX_CHARACTERS_DESC_INPUT = 250
    const val MONUMENT_ZOOM = 15f
    const val UPDATE_INTERVAL_MILLIS = 10000L
    const val FASTEST_UPDATE_INTERVAL_MILLIS = 5000L
    const val FAVORITE_CHECK = "Check"
    const val FAVORITE_UNCHECK = "UnCheck"
    const val OPEN_GALLERY_OPTION = 0
    const val OPEN_CAMERA_OPTION = 1
    const val CLOSE_OPTION = 2
    const val IMAGE_BUFFER = 4 * 1024
    const val EOF = -1
    const val MY_MONUMENTS_TITLE = "My Monuments"
    const val FAVORITES_TITLE = "Favorites"
    const val DELETE_DIALOG_TAG = "DeleteGameDialog"
    const val DEFAULT_LOCATION_LATITUDE = 0.0
    const val DEFAULT_LOCATION_LONGITUDE = 0.0
    const val PADDING_MAP = 100
    const val DENIED_PERMISSIONS = "Permiso denegado"
    const val ERROR_FAVORITES_FOUND = "No favorite monuments found"
    const val ERROR_LOADING_FAVORITES = "Error loading favorite monuments"
    const val ERROR_MY_MONUMENTS_FOUND = "No favorite monuments found"
    const val ERROR_LOADING_MY_MONUMENTS = "Error loading favorite monuments"
    const val ERROR_LOADING_MONUMENTS = "Error loading monuments"
}